FROM node:22-alpine

RUN npm install -g npm@latest

WORKDIR /usr/src/app

ADD ./front-end/package*.json ./

# Add bash
RUN apk update && apk add --no-cache bash

# Change shell representation (removing Docker ID as info)
RUN echo 'export PS1="\w\\$ "' >> ~/.bashrc

# Change default shell to bash
RUN sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

ENTRYPOINT ["bash" , "-c"]

